=== baroudim/LangagePourLeWeb/Tux/src/xsd/dico.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<schema version="1.0"
           targetNamespace="http://myGame/tux"
           xmlns="http://www.w3.org/2001/XMLSchema"
           xmlns:tux="http://myGame/tux"
           elementFormDefault="qualified">
    <element name="dictionnaire" type="tux:Dictionnaire"/>
    <complexType name="Dictionnaire">
        <sequence>
            <element name="mot" type="tux:Mot"  maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="Mot"><!-- ajout attribut sur un type simple -->
        <simpleContent>
            <extension base ="tux:Motdic"><!-- motdic patterne//type simple du contenu -->
                <attribute name = "niveau" type ="tux:Niveau"/>
            </extension>
        </simpleContent>
    </complexType>
    <simpleType name="Niveau">
        <restriction base="int">
            <enumeration value="1"/>
            <enumeration value="2"/>
            <enumeration value="3"/>
            <enumeration value="4"/>
            <enumeration value="5"/>
        </restriction>
    </simpleType>
    <simpleType name="Motdic">
        <restriction base="string">
            <pattern value="[a-zéèàùê]+(-[a-zéèàùê]*)?"/>            
        </restriction>
    </simpleType>
</schema>

=== baroudim/LangagePourLeWeb/Tux/src/XML/dico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<dictionnaire 
xmlns ="http://myGame/tux"
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://myGame/tux ../xsd/dico.xsd'>
    
    <mot niveau = "1" >papa</mot>
    <mot niveau = "1" >maman</mot>
    <mot niveau = "1" >bonbon</mot>
    <mot niveau = "1" >manger</mot>
    <mot niveau = "1" >dormir</mot>
    <mot niveau = "1" >chanter</mot>
    <mot niveau = "1" >jeux</mot>
    <mot niveau = "1" >porte</mot>
    <mot niveau = "2" >chat</mot>
    <mot niveau = "2" >chien</mot>
    <mot niveau = "2" >tomate</mot>
    <mot niveau = "2" >fraise</mot>
    <mot niveau = "2" >pomme</mot>
    <mot niveau = "2" >banane</mot>
    <mot niveau = "2" >lapin</mot>
    <mot niveau = "3" >feutre</mot>
    <mot niveau = "3" >brosse</mot>
    <mot niveau = "3" >chaise</mot>
    <mot niveau = "3" >cheveux</mot>
    <mot niveau = "3" >cerise</mot>
    <mot niveau = "4" >histoire</mot>
    <mot niveau = "4" >abeille</mot>
    <mot niveau = "4" >police</mot>
    <mot niveau = "4" >vase</mot>
    <mot niveau = "5" >trompette</mot>
    <mot niveau = "5" >flute</mot>
    <mot niveau = "5" >camion</mot>
    <mot niveau = "5" >zebre</mot>
</dictionnaire>
